### ISSUE TITLE
Change package name

### ISSUE THREAD

**Issue by mopeneko** [sakura-rip/pythonlike-go#1]
> By convention, packages are given lower case, single-word names; there should be no need for underscores or mixedCaps.

https://golang.org/doc/effective_go#package-names

But in the code,

https://github.com/sakura-rip/pythonlike-go/blob/1a68ef4cc3706636ab45726557cee12a948cb2d3/list.go#L1

So we need to change it to `pythonlikego` or others.

**Comment by sakura-rip** [comment]
fixed
